### ISSUE TITLE
Algervard Havoc Demon Hunter Meta/Blade Dance Keybind Showing Wrong

### ISSUE THREAD

**Issue by Quttzik** [Hekili/hekili#1186]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Blade Dance is bound to X  Chaos Strike is bound to W   Which meta Empowers both of those attacks.    So when I meta  Blade Dances icon changes to show it is empowered but it is still on X   But Hekili is telling me to hit W which is now empowered Chaos strike But the Icon Hekili is showing when its telling me to hit W is the Empowered Chaos strike and if I hit W like it tells me the Rotation doesn't move forward until I hit X with the empowered Blade Dance. 
Per Another suggestion made to another user I did a manual override both Chaos Strike and Blade Dance abilities to set those keybinds however still when empowered it shows W for Blade Dance. 

### How to Reproduce

1. Enter game as havoc DH
2. Have Blade Dance and Chaos Strike Keybound. 
3. Follow the Rotation thru once normally
4. Activate Metamorphosis and follow rotation until Blade Dance comes up again. 

### Snapshot (Link)

https://pastebin.com/KzY7u2c1   ##Before Metamorphosis
https://pastebin.com/0iyhr68H    ##After Metamorphosis

### Additional Information

 snipboard.io/BIgmdJ.jpg             ##Screenshot Showing Icons

**Comment by Hekili** [comment]
This likely has more to do with how you've organized your bars, keybind detection is pretty finicky in that regard.

You can manually set the keybind in /hekili > Actions. You'll want to do that for both Blade Dance and whatever Blade Dance becomes during Metamorphosis.
