### ISSUE TITLE
Anniversary Patch 11.0.5 Status Tracker

### ISSUE THREAD

**Issue by syrifgit** [Hekili/hekili#3983]
### APLs are not up to us, they will be added as they are completed by the Theorycrafters and added to SIMC.

See the following list for a status update on specs that have had addon-impacting changes

#### Hunter
  - [x] BM
  - [x] MM
  - [x] Surv
#### Death Knight
 - [x] Deathbringer tree
 - [x] BDK
#### Druid
 - [x] Druid of the claw tree
 - [x] Balance
 - [x] Resto
#### Evoker
 - [x] Base class stuff
 - [x] Devestation
#### Mage
 - [x] Frostfire tree
 - [x] Spellslinger tree
 - [x] Arcane
 - [x] Fire
 - [x] Frost
#### Monk
 - [x] Shado-Pan tree
 - [x] MW
 - [x] WW
#### Paladin (Why would they do this do they hate us?)
 - [x] Base class stuff
 - [x] Lightsmith
 - [x] Holy
 - [x] Prot
#### Priest
 - [x] Archon
#### Rogue
 - [x] Base class stuff
 - [x] Fatebound
 - [x] Trickster
 - [x] Sin
 - [x] Outlaw
 - [x] Subtlety
#### Shaman
 - [x] Stormbringer
 - [x] Elemental
 - [x] Enhance
 - [x] Resto
#### Warlock
 - [x] Destruction

**Comment by Hekili** [comment]
Released!
