### ISSUE TITLE
Patch 11.1 rework tracking

### ISSUE THREAD

**Issue by syrifgit** [Hekili/hekili#4256]
## Complete as of Jan 23rd notes
- [x] #4294
  - [x] Proper documentation/notes written
  - [x] Fully tested in-game on PTR
- [x] #4295 @syrifgit 
  - [x]  Proper documentation/notes written
  - [x] Fully tested in-game on PTR
- [x] #4301 @syrifgit 
  - [x] Proper documentation/notes written
  - [x] Fully tested in-game on PTR
- [x] #4303
  - [x] Proper documentation/notes written
  - [x] Fully tested in-game on PTR
- [x] #4292 @syrifgit 
  - [x] Proper documentation/notes written
  - [ ] Fully tested in-game on PTR
  - [ ] Only remaining item: Ice Lances empowered by Fingers of Frost no longer consume Winter’s Chill.
- [x] #4300
  - [x] Proper documentation/notes written
  - [ ] Fully tested in-game on PTR
- [x] #4298
  - [x] Proper documentation/notes written
  - [ ] Fully tested in-game on PTR
- [x] #4293
  - [x] Proper documentation/notes written
  - [ ] Fully tested in-game on PTR
- [x] #4297 @syrifgit 
  - [x] Proper documentation/notes written
  - [x] Fully tested in-game on PTR
- [x] #4304
  - [x] Proper documentation/notes written
  - [ ] Fully tested in-game on PTR
- [x] #4296
  - [x] Proper documentation/notes written
  - [x] Fully tested in-game on PTR
- [x] #4302
  - [x] Proper documentation/notes written
  - [ ] Fully tested in-game on PTR
  - [ ] Final remaining item: Surging Totem - Gains a relocation spell to summon nearby without triggering the global cooldown (6-second cooldown).
- [x] #4299
  - [x] Proper documentation/notes written
  - [ ] Fully tested in-game on PTR
  - [ ] Just waiting for Hpal talents to hit PTR
- [x] #4317

**Comment by syrifgit** [comment]
## Marksmanship Hunter Example
```
spec:RegisterGear( "tww2", 229271, 229272, 229274, 229270, 229273 )
spec:RegisterAuras( {
    -- 2-set
    -- https://www.wowhead.com/spell=1218033
    -- Jackpot! Auto shot damage increased by 200% and the time between auto shots is reduced by 0.5 sec.  
    jackpot = {
        id = 1218033,
        duration = 10,
        max_stack = 1,
    },
    tier_4_set_placeholder = {
        id = 12345,
        duration = 10,
        max_stack = 1,
    },

} )
```

**Comment by darkmullac** [comment]
Ret paladin - 

Head - 229244
Shoulder - 229242
Legs - 229243
Gloves - 229245
Chest - 229247

2 set bonus 

SpellID - 1216828
IconID - 4667423

10 stacks of winning streak increasing Divine storm and templars verdict by 2% each time 

4 set 

SpellID 1216837
IconID 133785

When Winning streak ends you get your last spent holy power back and for 4 seconds you can't lose holy power and your damage is increased by 10%  


https://pastebin.com/dCNEdL45

**Comment by yokaii4** [comment]
### Frost Mage
Spec: frost
tier set IDs: 229346, 229344, 229342, 229343, 229341

2-set buff

spells have a chance to proc a jackpot that generates a frostbolt valley hitting a primary target and spreading to surrounding mobs (until 8). Casting Icy Veins always procs it

frostbolt volley ID: 1216910

4-set buff

extended bankroll id - 1216914

Icy veins procs it at 100% effectiveness every 10 sec for 30s

Skeleton pastebin: ThisIsTotallyALink

Changed talents: 

1.  was ID: 382103 - is: 1216953

---

### Arcane Mage
Spec: arcane
tier set IDs: 229346, 229344, 229342, 229343, 229341

2-set buff

spells have minimal chances of granting Clearcasting + 8% more dps for 12s. Touch of the Magi always procs Jackpot

4-set buff

When you hit Jackpot you gain Aether Attunement at 100% effectiveness 

Aether attunement ID: 453601

Skeleton pastebin: ThisIsTotallyALink

Changed talents: none

--- 

### Fire Mage
Spec: fire
tier set IDs: 229346, 229344, 229342, 229343, 229341

2-set buff

spells have chances of getting Jackpot, which decreases Combustion cd by 3s. Using Combustion always procs Jackpot at 200% effectiveness
4-set buff

When you hit Jackpot you gain 7% more dps for 12s. If you gain jackpot from combustion the duration is increased by 100%

Skeleton pastebin: ThisIsTotallyALink

Changed talents: none

--- 

### Current changes list (Jan 11th 2025)
https://www.gameleap.com/articles/wow-tww-11-1-development-notes-mage-changes#:~:text=Pyrotechnics%20has%20been%20updated%20%E2%80%93%20Critical,when%20Combustion%20is%20not%20active.

**Comment by yokaii4** [comment]
### DH HAVOC

spec:RegisterGear( "tww2", 229316, 229314, 229319, 229317, 229315 )
spec:RegisterAuras( {
    -- 2-set
    -- Winning Streak! Increase the DPS of Blade Dance and Chaos Strike by 3% stacking pu to 10 times. Blade Dance and Chaos Strike have 15% chance of removing Winning Streak! .  
    jackpot = {
        id = 1217011,
        duration = until Blade Dance/Chaos Strike removes it
        max_stack = 10,
    },
--4-set
-- Winning Streak persists for 7s after being cancelled. Entering Demon Form sacrifices all Winning Streak! stacks to gain 0% (?) Crit Strike Chance per stack consumed. Lasts 15s
    tier_4_set_placeholder = {
        id = 1217055,
        duration = 15
        max_stack = 1,
    },

} )

**Comment by Bingo176** [comment]
**Feral Druid**

pec:RegisterGear( "tww2", 229307, 229305, 229310, 229308, 229306 )
spec:RegisterAuras( {
    -- 2-set
    -- https://www.wowhead.com/ptr-2/spell=1217236/winning-streak
    -- Your spells and abilities have a chance to activate a Winning Streak! increasing the damage of your Ferocious Bite, Rip, and Primal Wrath by 3% stacking up to 10 times. Ferocious Bite, Rip, and Primal Wrath have a 15% chance to remove Winning Streak!
    Winning Streak! = {
        id = 1217236,
        duration = 10,
        max_stack = 10,
    },
    tier_4_set_placeholder = {
-- https://www.wowhead.com/ptr-2/spell=1217245/big-winner
        id = 1217245,
        duration = 6,
        max_stack = 1,
    },

} )

**Comment by Bingo176** [comment]
**Guardian Druid**

pec:RegisterGear( "tww2", 229307, 229305, 229310, 229308, 229306 )
spec:RegisterAuras( {
    -- 2-set
    -- https://www.wowhead.com/ptr-2/spell=1218553/luck-of-the-draw
    -- Each time you take damage you have a chance to activate Luck of the Draw! causing you to cast Survival Instincts for 4.0 sec. Your damage done is increased by 15% for 8 sec after Luck of the Draw! activates.
 Luck of the Draw! = {
        id = 1218553,
        duration = 8,
        max_stack = 1,
    },
    tier_4_set_placeholder = {
-- https://www.wowhead.com/ptr-2/spell=1218537/stacked-deck
--After you gain Luck of the Draw! your next 10 Druid abilities cast another Druid ability at 125% effectiveness.
        id = 1218537,
        duration = 20,
        max_stack = 10,
    },

} )

**Comment by Bingo176** [comment]
**Ret Paladin**


spec:RegisterGear( "tww2", 229244, 229242, 229247, 229245, 229243 )
spec:RegisterAuras( {
    -- 2-set
    -- https://www.wowhead.com/ptr-2/spell=1216828/winning-streak
    -- Your spells and abilities have a chance to activate a Winning Streak! increasing the damage of your Templar's Verdict and Divine Storm by 2% stacking up to 10 times. Spending Holy Power on damaging abilities has a 12% chance to remove Winning Streak!
    Winning Streak! = {
        id = 1216828,
        duration = 30,
        max_stack = 10,
    },
    tier_4_set_placeholder = {
-- https://www.wowhead.com/ptr-2/spell=1216837/all-in
        id = 1216837,
        duration = 4,
        max_stack = 1,
    },

} )

**Comment by Bingo176** [comment]
**Prot Paladin**

pec:RegisterGear( "tww2", 229244, 229242, 229247, 229245, 229243 )
spec:RegisterAuras( {
    -- 2-set
    -- https://www.wowhead.com/ptr-2/spell=1218114/luck-of-the-draw
    -- Each time you take damage you have a chance to activate Luck of the Draw! causing you to cast Guardian of Ancient Kings for 4.0 sec. Your damage done is increased by 15% for 10 sec after Luck of the Draw! activates.
    Winning Streak! = {
        id = 1218114,
        duration = 10, (extendable with 4pc for another 10 seconds)
        max_stack = 1, 
    },
    tier_4_set_placeholder = {
--https://www.wowhead.com/ptr-2/spell=1218114/luck-of-the-draw
--While you have Luck of the Draw! Shield of the Righteous refunds 1-3 Holy Power and extends the duration of Luck of the Draw! by 0.5 sec, up to 10 sec.
        id = 1218114,
        duration = 10, (extendable with 4pc for another 10 seconds)
        max_stack = 1,
    },

} )

**Comment by syrifgit** [comment]
Thanks to all who helped, 11.1 is ready as of yesterday's patch notes

**Comment by syrifgit** [comment]
It's all ogre
